version: "3"

services:
  compiler-explorer:
    build:
      context: ./
      dockerfile: Dockerfile
    image: compiler-explorer-archlinux:latest
    container_name: compiler-explorer-archlinux
    ports:
      - 10240:10240
    networks:
      - ce_network
    restart: on-failure
    stop_grace_period: 1m30s
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 512M

networks:
  ce_network:
