# Package base-devel
# 1) archlinux-keyring  2) autoconf  3) automake  4) binutils  5) bison
# 6) debugedit  7) file  8) findutils  9) flex  10) gawk
# 11) gcc 12) gettext  13) grep  14) groff  15) gzip
# 16) libtool  17) m4  18) make  19) pacman  20) patch
# 21) pkgconf  22) sed  23) sudo 24) texinfo  25) which

[min-base]
base-devel = true
# ------------------------------
git = true
vim = true
zsh = true
# ------------------------------
mandoc = true
net-tools = true
openssh = true
sshpass = true
wget = true
xclip = true
curl = true
# ------------------------------
python = true
python-pip = true
# ------------------------------
fzf = true
tmux = true
ripgrep = true

[rec-base]  # :min-base
# ------------------------------
bat = true
exa = true
fd = true
ncdu = true
nnn = true
tmuxp = true
# ------------------------------
aria2 = true
rsync = true
# ------------------------------
reflector = true
tldr = true
github-cli = true

[max-base]  # :rec-base
hexyl = true
neofetch = false
tig = true


[min-dev]
# C++
clang = true
# vim coc
nodejs = true
npm = true
# python
yapf = true  # python format

[rec-dev]  # :min-dev
cppcheck = true
cmake = true
# source code viewer
cscope = true
ctags = true
# debug tools
gdb = true
hyperfine = true
valgrind = true
radare2 = true

[max-dev]  # :max-dev
# build tools
bazel = false
scons = false
# C++ third party library
abseil-cpp = false
fmt = false
doctest = false
gtest = false
boost = false

