# This file is used for script ~/bin/gh_repo_clone_from_config
# When you run the script, it will automatically sync the repos below.
# Syntax:
# - repository: <ESSENTIAL>
#   directory: <ESSENTIAL>
#   gitflags: <OPTIONAL>
#     depth: <OPTIONAL>
#     branch: <OPTIONAL>
#
############################################################
# Example:

# TensorFlow
- repository: tensorflow/tensorflow
  directory: ~/github/machinelearning/tensorflow
  gitflags:
    depth: 1
    branch: v2.13.0

# TensorFlow examples
- repository: tensorflow/examples
  directory: ~/github/machinelearning/tensorflow_examples
  gitflags:
    depth: 1
############################################################
