[tools]
# global tool versions go here
# you can set these with `mise use -g`
# go = 'latest'
# java = 'lts'
# node = 'lts'
# python = '3.10'

[settings]
# plugins can read the versions files used by other version managers (if enabled by the plugin)
# for example, .nvmrc in the case of node's nvm
legacy_version_file = true

# configure `mise install` to always keep the downloaded archive
always_keep_download = false # deleted after install by default
always_keep_install = false  # deleted on failure by default

plugin_autoupdate_last_check_duration = 0 # disable updates

# config files with these prefixes will be trusted by default
trusted_config_paths = ['~']

verbose = false     # set to true to see full installation output, see `MISE_VERBOSE`
asdf_compat = false # set to true to ensure .tool-versions will be compatible with asdf, see `MISE_ASDF_COMPAT`
jobs = 8            # number of plugins or runtimes to install in parallel. The default is `4`.
raw = false         # set to true to directly pipe plugins to stdin/stdout/stderr
yes = true          # set to true to automatically answer yes to all prompts

disable_default_shorthands = false # disable the default shorthands, see `MISE_DISABLE_DEFAULT_SHORTHANDS`
disable_tools = [
    'ruby',
] # disable specific tools, generally used to turn off core tools

experimental = true # enable experimental features
