version: "3"

services:
  jupyter:
    build:
      context: ./
      dockerfile: Dockerfile
    image: jupyter:latest
    container_name: jupyter
    working_dir: /home/jovyan/jupyter-notebook
    environment:
      - CHOWN_HOME=yes
      - GRANT_SUDO=yes
    ports:
      - "8888:8888/tcp"
    volumes:
      - '~/jupyter-notebook:/home/jovyan/jupyter-notebook'
